//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestGest
{
    using System;
    using System.Collections.Generic;

    public partial class Trabalhador : Pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabalhador()
        {
            this.Pedido = new HashSet<Pedido>();
        }

        public decimal Salario { get; set; }
        public string Posicao { get; set; }
        public int RestauranteId { get; set; }

        public virtual Restaurante Restaurante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }

        public virtual Pessoa Pessoa { get; set; }
        public virtual Restaurante restaurante { get; set; }


        public override string ToString()
        {
            return this.Posicao + " " + this.Pessoa.ToString();
        }

    }
}
